# Language: python sets up virtualenv and pip that we don't need and
# osx builders does not support: https://github.com/travis-ci/travis-ci/issues/2312


# TBA needs > 4 Gb system, selecting sudo
# Increases available RAM to 7.5 Gb
# https://docs.travis-ci.com/user/reference/overview/
sudo: true

matrix:
  include:
    - os: linux
      language: python
      dist: trusty
      env:
         - TRAVIS_PYTHON_VERSION=2.7
    - os: linux
      language: python
      env:
         - TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      osx_image: xcode8
      env:
        - TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      osx_image: xcode8
      env:
        - TRAVIS_PYTHON_VERSION=3.6

notifications:
  email:
    - pohl@physik.uni-bonn.de
    
cache:
  directories:
  - $HOME/.pip-cache/

 
# Setup gcc 4.9 compiler and miniconda python with needed packages
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINICONDA_OS=Linux ;
      else
        MINICONDA_OS=MacOSX ;
    fi ;
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # - source "$HOME"/miniconda/bin/activate root
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  #- conda create -q -n tba python="$TRAVIS_PYTHON_VERSION" pip
  - python -c "from distutils import sysconfig;print(sysconfig.get_config_var('LDSHARED'))"
  #- source activate tba
  #- python -c "from distutils import sysconfig;print(sysconfig.get_config_var('LDSHARED'))"
  - conda install numpy cython pytables scipy matplotlib nose numba mock pytest-cov pyyaml
  # - https://bugs.python.org/issue30915
  - pip install --upgrade pip
  - pip install progressbar-latest xvfbwrapper coverage python-coveralls pixel_clusterizer pylandau pytest
  - pip install -r requirements_docs.txt
  - python setup.py develop
  - printenv | sort

# Run test
script:
  # Hack to allow tests coverage in multi processes, http://coverage.readthedocs.org/en/latest/subprocess.html
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      touch $HOME/miniconda/lib/python2.7/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python2.7/site-packages/converage.pth;
    else
      touch $HOME/miniconda/lib/python3.6/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python3.6/site-packages/converage.pth;
    fi
  - travis_wait 40 py.test --cov=testbeam_analysis
  
after_success:
  - coveralls --data_file .coverage.*

deploy:
  provider: script
  script: scripts/create_doc.sh
  on:
    branch: development
  
