# language: python sets up virtualenv and pip that we don't need.
# omitting language gives us ruby stuff. c seems likely to be a minimal setup.
language: c
# this is here to avoid a hang with python 2.7, suggested in
# https://github.com/travis-ci/travis-ci/issues/6861
sudo: required

env:
  # All supported python versions
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.6

os:
  - linux
  - osx
 
# TBA needs > 4 Gb system, selecting sudo
# Increases available RAM to 7.5 Gb
# https://docs.travis-ci.com/user/reference/overview/
sudo: true

dist: trusty

notifications:
  email:
    - pohl@physik.uni-bonn.de
    
cache:
  directories:
  - $HOME/.pip-cache/
 
# Setup miniconda python with needed packages
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINICONDA_OS=Linux ;
      else
        MINICONDA_OS=MacOSX ;
    fi ;
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME"/miniconda/bin/activate root
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pip
  - source activate test-environment
  - printenv | sort
  - conda install numpy cython pytables scipy matplotlib nose numba mock pytest-cov pyyaml
  - pip install progressbar-latest xvfbwrapper coverage python-coveralls pixel_clusterizer pylandau pytest
  - pip install -r requirements_docs.txt
  - python setup.py develop

# Run test
script:
  # Hack to allow tests coverage in multi processes, http://coverage.readthedocs.org/en/latest/subprocess.html
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      touch $HOME/miniconda/lib/python2.7/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python2.7/site-packages/converage.pth;
    else
      touch $HOME/miniconda/lib/python3.6/site-packages/converage.pth && printf "import coverage; coverage.process_startup()" > $HOME/miniconda/lib/python3.6/site-packages/converage.pth;
    fi
  - travis_wait 40 py.test --cov=testbeam_analysis
  - sphinx-build docs docs/_build/html
  
after_success:
  - coveralls --data_file .coverage.*  
  # DOCS 
  - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
  - openssl aes-256-cbc -K $encrypted_ba29598036fd_key -iv $encrypted_ba29598036fd_iv -in docs/key.enc -out docs/key -d && ssh-add docs/key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
  - export ${!TRAVIS*} 
  - sphinx-versioning push -r development -w master -w development -b docs gh-pages .
  
